name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libegl-dev libudev-dev libvulkan1 mesa-vulkan-drivers libgl1-mesa-dri mesa-opencl-icd vulkan-tools vulkan-utils
    - name: Check vulkan
      run: vulkaninfo
    - name: Install nightly Rust
      run: rustup toolchain add nightly
    - name: Build
      run: cargo +stable run --verbose
    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: |
          capture.png
    - name: Run tests
      run: cargo +nightly test --verbose
